version: "3.9"
services:
  client:
    container_name: booking-app-client
    image: booking-app-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_PUBLIC_URL: ${VITE_PUBLIC_URL}
        VITE_SOKET_URL: ${VITE_SOKET_URL}
    restart: always
    ports:
      - 80:3000

  server:
    container_name: booking-app-server
    image: booking-app-server
    network_mode: "host"
    volumes:
      - /home/ubuntu/public:/public
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
        MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@127.0.0.1:27017/admin
        JWT_SECRET: ${JWT_SECRET}
        JWT_TOKEN_AUDIENCE: ${JWT_TOKEN_AUDIENCE}
        JWT_TOKEN_ISSUER: ${JWT_TOKEN_ISSUER}
        JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
        JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
        REQUEST_USER_KEY: ${REQUEST_USER_KEY}
        SOKET_ORIGIN: ${SOKET_ORIGIN}
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    network_mode: "host"
    volumes:
      - /home/ubuntu/mongo/db:/data/db
      - /home/ubuntu/s3cloud:/home/root/backup
      - /home/ubuntu/mongoconf/mongod.conf:/etc/mongod.conf
      - /home/ubuntu/script:/home/root/script
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: "exit 0"
