version: "3.9"
services:
  client:
    container_name: booking-app-client
    image: booking-app-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_PUBLIC_URL: ${VITE_PUBLIC_URL}
    restart: always
    ports:
      - 3000:3000

  server:
    container_name: booking-app-server
    image: booking-app-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
        MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
        JWT_SECRET: ${JWT_SECRET}
        JWT_TOKEN_AUDIENCE: ${JWT_TOKEN_AUDIENCE}
        JWT_TOKEN_ISSUER: ${JWT_TOKEN_ISSUER}
        JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
        JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
        REQUEST_USER_KEY: ${REQUEST_USER_KEY}
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: "exit 0"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
