version: "3.9"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: app-nginx
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  client:
    container_name: app-client
    image: app-client
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_PUBLIC_URL: ${VITE_PUBLIC_URL}
        VITE_SOKET_URL: ${VITE_SOKET_URL}
    restart: always

  server:
    container_name: app-server
    image: app-server
    network_mode: "host"
    volumes:
      - "/home/ubuntu/public:/app/public"
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
        MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@127.0.0.1:27017/admin
        JWT_SECRET: ${JWT_SECRET}
        JWT_TOKEN_AUDIENCE: ${JWT_TOKEN_AUDIENCE}
        JWT_TOKEN_ISSUER: ${JWT_TOKEN_ISSUER}
        JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
        JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
        REQUEST_USER_KEY: ${REQUEST_USER_KEY}
        SOKET_ORIGIN: ${SOKET_ORIGIN}
        DOMAIN: ${DOMAIN}
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    container_name: app-db
    restart: always
    volumes:
      - "/home/ubuntu/mongo/db:/data/db"
      - "/home/ubuntu/s3cloud:/home/root/backup"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: "exit 0"
