export enum RoutesEnum {
  SignIn = "/",
  SignUp = "/sign-up",
  ServerError = "/error",
  Profile = "/profile",
  Search = "/search",
  Result = "/result",
  Room = "/room",
  EditRoom = "/editroom",
  AddRoom = "/addroom",
  ClientBookings = "/bookings/client",
  Hotels = "/hotels",
  Hotel = "/hotel",
  AddHotel = "/addhotel",
  EditHotel = "/edithotel",
  Users = "/users",
  AddUser = "/adduser",
  SupportRequests = "/supportrequests",
  SupportRequest = "/supportrequest",
  CreateSupportRequest = "/supportrequest/create",
  ManagerBookingsSearch = "/manager/bookings",
  ManagerUsersSearch = "/manager/users",
  ManagersSupportRequestsBoard = "/manager/supportrequests",
  Id = "/:id",
}
