export enum RoutesEnum {
  SignIn = "/",
  SignUp = "/sign-up",
  ServerError = "/error",
  Profile = "/profile",
  Search = "/search",
  Result = "/result",
  Room = "/room",
  EditRoom = "/editroom",
  AddRoom = "/addroom",
  Bookings = "/bookings",
  Hotels = "/hotels",
  Hotel = "/hotel",
  AddHotel = "/addhotel",
  EditHotel = "/edithotel",
  Users = "/users",
  SupportRequests = "/supportrequests",
  SupportRequest = "/supportrequest",
  Id = "/:id",
}
